---
# Tasks to configure firewalld rules

- name: Determine if firewalld is running
  command: firewall-cmd --state
  register: firewalld_running
  ignore_errors: true
  changed_when: false

- name: Enable firewalld ports
  firewalld:
    port: '{{item}}'
    permanent: true
    state: enabled
  when: firewalld_running.rc == 0
  with_items: firewalld_ports
  notify: reload firewalld
