---
- hosts: srv3
  tasks:
  - name: Add user 1
    # Add a user and generate ssh key within .ssh directory located within the home.
    user: name=deployuser shell=/bin/bash comment="Deployment user" generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
  - name: Add user 2
    user: name=cmills comment=cmills shell=/bin/bash comment="Admin user"
  -  authorized_key: user=cmills key="{{ lookup('file', '/home/oss/.ssh/id_rsa.pub') }}"
