---
- hosts: '{{servername}}'
  vars:
    zserver: 107.170.116.31
  tasks:
    - name: Download zabbix agent for Ubuntu Precise amd 64 version
      get_url: url=http://repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix/zabbix-agent_2.2.4-1+precise_amd64.deb dest=/tmp mode=644

    - name: Install zabbix agent
      command: dpkg -i /tmp/zabbix-agent_2.2.4-1+precise_amd64.deb
      ignore_errors: yes

    - name:  Configure zabbix agent
      lineinfile: dest=/etc/zabbix/zabbix_agentd.conf state=present regexp="Server=127.0.0.1" line="Server={{zserver}}"

    # Make sure zabbix agent is set to start after a restart
    - name:  Set zabbix agent to start automatically
      service: name=zabbix-agent enabled=yes

    # zabbix agent needs to be restarted to resgiter changes made above
    - name: Restart zabbix agent
      service: name=zabbix-agent state=restarted
