---
- hosts: srv3
  tasks:
  - name: Update httpd (apache) to the latest version
    apt: name=apache2 state=latest
    notify:
    - restart apache


  - name: Ensure httpd (apache) is running and enabled at boot
    service: name=apache2 state=started enabled=yes
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
