## Variables passed in are servername,pass and user
## servername is the URL of the zabbix server
## User if the username and pass is the password for the user
---
- hosts: '{{servername}}'
  gather_facts: no
  tasks:
    - name: Create a new host or update an existing host's info
      local_action:
        module: zabbix_host
        server_url: http://107.170.116.31/zabbix
        login_user: '{{user}}'
        login_password: '{{pass}}'
        host_name: srv2.opensitesolutions.com
        status: enabled
        state: present
        host_groups:
          - oss
        link_templates:
        # You can find the name of the template under Configuration - Templates, select the template
        # under the template column click on the template, use the 'Template name'
          - templae_os_web
        # inventory_mode: automatic
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: 64.62.228.207
            dns: ""
            port: 10050
