---
- name: Determine the timestamp for the backup.
  set_fact:
    now: '{{ lookup("pipe", "date +%F-%T") }}'

- name: Create a directory for a database backup to live.
  file:
    path: '{{ backup_dir.rstrip("/") }}/{{ now }}/'
    group: postgres
    mode: 0775
    owner: root
    state: directory
  notify: Remove the backup directory.
