---
- name: Determine whether System Tracking is enabled
  shell: tower-manage uses_mongo
  changed_when: no
  ignore_errors: yes
  register: result

- name: Perform a MongoDB dump (internal).
  shell: mongodump --db system_tracking --out system_tracking.db
  args:
    chdir: '{{ backup_dir.rstrip("/") }}/{{ now }}/'
  when: result.rc == 0 and database == 'internal'

- name: Perform a MongoDB dump (external).
  shell: mongodump --host {{ mongo_host }} --port {{ mongo_port }} --db {{ mongo_database }} --username {{ mongo_username }} --password {{ mongo_password }} --out system_tracking.db
  args:
    chdir: '{{ backup_dir.rstrip("/") }}/{{ now }}/'
  when: result.rc == 0 and database == 'external'
