---
- name: Perform a PostgreSQL dump.
  shell: pg_dump -d {{ pg_database }} --clean --create > tower.db
  args:
    chdir: '{{ backup_dir.rstrip("/") }}/{{ now }}/'
  sudo_user: postgres
  sudo: True
  when: database == 'internal'

- name: Perform a PostgreSQL dump.
  shell: PGPASSWORD="{{ pg_password }}" pg_dump --clean --create --host="{{ pg_host }}" --username="{{ pg_username }}" --dbname="{{ pg_database }}" > tower.db
  args:
    chdir: '{{ backup_dir.rstrip("/") }}/{{ now }}/'
  when: database == 'external'
