---
- name: Install Apache
  apt: pkg=apache2 state=present

- name: Copy configuration Clarence Mills domain file to server
  copy: src=clarencemills.com.conf dest=/etc/apache2/sites-available/

- name: Create web Domain directory clarencemills.com
  file: path=/var/www/clarencemills.com state=directory

- name: Create web domain directory becomeonewiththecode.com
  file: path=/var/www/becomeonewiththecode.com state=directory
  notify:
  - restart apache2
