---
- name: Copy configuration millsresidence.com domain file to server
  copy: src=millsresidence.com.conf dest=/etc/apache2/sites-available/

- name: Create symlink for millsresidence.com
  file: src=/etc/apache2/sites-available/millsresidence.com.conf dest=/etc/apache2/sites-enabled/millsresidence.com.conf state=link

- name: Create web domain directory millsresidence.com
  file: path=/var/www/millsresidence.com state=directory

- name: Copy web data
  copy: src=index.html dest=/var/www/millsresidence.com

- name: Create access log directory
  file: path=/var/log/apache2/millsresidence.com-access.log state=touch

- name: create error log
  file: path=/var/log/apache2/millsresidence.com-error.log state=touch

- name: remove default configuration  - disable default catch all site
  file: path=/etc/apache2/sites-available/000-default.conf state=absent

- name: Disable default site
  shell: a2dissite 000-default

- name: wait and restart
  pause: minutes=1
  notify:
   - restart apache
