---
- name: Copy configuration opensitesolutions.com domain file to server
  copy: src=opensitesolutions.com.conf dest=/etc/apache2/sites-available/

- name: Create symlink for opensitesolutions.com
  file: src=/etc/apache2/sites-available/opensitesolutions.com.conf dest=/etc/apache2/sites-enabled/opensitesolutions.com.conf state=link

- name: Create web domain directory opensitesolutions.com
  file: path=/var/www/opensitesolutions.com state=directory

- name: Create access log directory
  file: path=/var/log/apache2/opensitesolutions.com-access.log state=touch

- name: create error log
  file: path=/var/log/apache2/opensitesolutions.com-error.log state=touch

- name: remove default configuration  - disable default catch all site
  file: path=/etc/apache2/sites-available/000-default.conf state=absent

- name: Disable default site
  shell: a2dissite 000-default
  ignore_errors: true

- name: wait and restart apache2
  pause: minutes=1
  notify:
   - restart apache
