---
- name: Determine whether System Tracking is enabled locally
  shell: tower-manage uses_mongo --local
  changed_when: no
  ignore_errors: yes
  register: result_local

- name: Determine whether System Tracking is enabled anywhere
  shell: tower-manage uses_mongo
  changed_when: no
  ignore_errors: yes
  register: result

- name: Start MongoDB if it is needed
  service:
    name: mongod
    state: started
    enabled: yes
  when: result_local.rc == 0
  
- name: Perform a MongoDB restore (internal).
  shell: mongorestore --drop --db system_tracking system_tracking.db/system_tracking
  args:
    chdir: '{{ backup_dir.rstrip("/") }}/restore/'
  when: result.rc == 0 and database == 'internal'

- name: Perform a MongoDB restore (external).
  shell: mongorestore --drop --host {{ mongo_host }} --port {{ mongo_port }} --db {{ mongo_database }} --username {{ mongo_username }} --password {{ mongo_password }} system_tracking.db/system_tracking
  args:
    chdir: '{{ backup_dir.rstrip("/") }}/restore/'
  when: result.rc == 0 and database == 'external'
