---
- name: Perform a PostgreSQL restore (internal).
  shell: psql < tower.db
  args:
    chdir: '{{ backup_dir.rstrip("/") }}/restore/'
  sudo: True
  sudo_user: postgres
  when: database == 'internal'

- name: Perform a PostgreSQL restore (external).
  shell: PGPASSWORD="{{ pg_password }}" psql --host="{{ pg_host }}" --username="{{ pg_username }}" --dbname="template1" < tower.db
  args:
    chdir: '{{ backup_dir.rstrip("/") }}/restore/'
  when: database == 'external'
