# http://docs.ansible.com/ansible/digital_ocean_module.html
---
- hosts: digitalocean
  tasks:
   - name: Create test droplet
     digital_ocean: 
       state: present
       command: droplet
       name: droptlet2
       # The below option makes this idempotent, it will not create duplicate droplets
       # with the same name.
       unique_name: yes
       #ssh_key_id:
       # An ID is created on instanciation of a new droplet, captured by the debug messages
       # below. Entering the field with the newly generated ID will stop creation of a new droplet
       # and will make changes if any to the droplet with the ID entered.
       #id: 13507942
       api_token: 6cbdb1572816b5bfab6c07309e9772ad4e030fb7df361e051ca744fa49cfc819
       size_id: 512mb
       region_id: ams2
       image_id: ubuntu-14-04-x64
       wait_timeout: 200
     register: my_droplet

   - debug: msg="ID is {{ my_droplet.droplet.id }}"
   - debug: msg="IP is {{ my_droplet.droplet.ip_address }}"
   
     #authorized_key: user=root key="{{ lookup('file', '/home/oss/.ssh/id_rsa.pub') }}"
