# Create,delete Digital ocean droplets
# http://docs.ansible.com/ansible/digital_ocean_module.html
---
- hosts: digitalocean
  tasks:
   - name: Manage "{{servername}}" droplet
     digital_ocean:
       state: "{{state}}"
       command: droplet

       # The below option makes this idempotent, it will not create duplicate droplets
       # with the same name.
       unique_name: yes

       # ssh_key_ids can be obtained from the digitalocean console, it's the unique key options
       # in brackets () beside the key name.
       # This will add the publick key from the console to root's authorizeds_keyfile during the VM setup
       ssh_key_ids: 6c:3c:f2:57:ed:b6:56:56:91:d2:84:e2:06:c7:43:d6

       # An ID is created on instanciation of a new droplet, captured by the debug messages
       # below. Entering the field with the newly generated ID will stop creation of a new droplet
       # and will make changes if any to the droplet with the ID entered.
       #id: 13507942
       id: "{{droplet_id}}"

       name: "{{servername}}"
       api_token: 257b1355f0df9f092e7a42db597f85cfafcc6dbc1ac27184a280e77ba64c5556
       size_id: 512mb
       region_id: nyc2
       image_id: ubuntu-14-04-x64
       wait_timeout: 200
     register: my_droplet

   - debug: msg="ID is {{ my_droplet.droplet.id }}"
   - debug: msg="IP is {{ my_droplet.droplet.ip_address }}"
