# http://docs.ansible.com/ansible/digital_ocean_module.html
# Spin up a new droplet.
# Accept state {{ sense }} whether ansent or present and accetp the name of the variable {{ name }}
---
- hosts: digitalocean
  gather_facts: true
  tasks:
   - name: Create test droplet
     digital_ocean: 
       state: "{{ sense }}"
       command: droplet
       name: "{{ name }}"

       # The below option makes this idempotent, it will not create duplicate droplets
       # with the same name.
       unique_name: yes
       
       # ssh_key_ids can be obtained from the digitalocean console, it's the unique key options
       # in brackets () beside the key name.
       # This will add the publick key from the console to root's authorizeds_keyfile during the VM setup 
       ssh_key_ids: 6c:3c:f2:57:ed:b6:56:56:91:d2:84:e2:06:c7:43:d6

       # An ID is created on instanciation of a new droplet, captured by the debug messages
       # below. Entering the field with the newly generated ID will stop creation of a new droplet
       # and will make changes if any to the droplet with the ID entered.
       #id: 13507942

       api_token: 6cbdb1572816b5bfab6c07309e9772ad4e030fb7df361e051ca744fa49cfc819
       size_id: 512mb
       region_id: nyc2
       image_id: ubuntu-14-04-x64
       wait_timeout: 200
     register: my_droplet

   - debug: msg="ID is {{ my_droplet.droplet.id }} - IP is {{ my_droplet.droplet.ip_address }}"

   - name: Add new droplet to host group
     local_action: add_host hostname={{ my_droplet.droplet.ip_address }} groupname=launched
