---
# tasks file for clarencemills.com
- name: Copy configuration Clarence Mills domain file to server
  copy: src=clarencemills.com.conf dest=/etc/apache2/sites-available/

- name: Create symlink for clarencemills.com
  file: src=/etc/apache2/sites-available/clarencemills.com.conf dest=/etc/apache2/sites-enabled/clarencemills.com.conf state=link

- name: Create web Domain directory clarencemills.com
  file: path=/var/www/clarencemills.com state=directory

- name: create access log
  file: path=/var/log/apache2/clarencemills.com-error.log state=touch

- name: Create error log
  file: path=/var/log/apache2/clarencemills.com-error.log state=touch

