---
# Specify the tower deb name used when installing tower.
tower_package_deb: '{{ tower_package_name }}={{ tower_package_version }}-*'

# Specify dependencies for running the tasks.
ubuntu_dependencies:
  - python-passlib  # Needed by htpasswd module
  - apache2-utils   # Needed by htpasswd command
  - python-psycopg2 # Needed by postgresql_* modules

# Indicate whether to verify gpg signatures during install
gpgcheck: 1
