---
- hosts: "{{ servername }}"
  vars:
    - base_dir: /tmp
    - dir: test
  tasks:
  - name: Check if "{{base_dir}}" directory is present
    stat: path=/tmp
    register: stat_status
    tags: check

  - name: Create "{{dir}}" directory in "{{base_dir}}" if it doesn't exist
    file: path="{{base_dir}}/{{dir}}" state=directory
    when: stat_status.stat.isdir and stat_status.stat.isdir is defined
    tags: create_dir

  - name: Remove "{{base_dir}}/{{dir}}" if it exist
    file: path="{{base_dir}}/{{dir}}" state=absent
    when: stat_status.stat.isdir and stat_status.stat.isdir is defined
    tags: remove_dir
