---
- hosts: "{{ servername }}"
  tasks:
  - name: Check if web directory is present
    stat: path=/tmp
    register: stat_status
    tags: check

  - name: Create new directory if it doesn't exist
    file: path=/tmp/test state=directory
    when: stat_status.stat.isdir
    tags: create_dir

  - name: Remove /tmp/test if it exist
    file: path=/tmp/test state=absent
    when: stat_status.stat.isdir is defined
    tags: remove_dir
