---
- hosts: "{{servername}}"
  vars_files:
    - vars_files/vagrant_files.yml
  tasks:

  - name: Build Vagrant file
    template:
      src: template_files/vagrant_file.j2
      dest: /tmp/Vagrantfile
      
