# Create,delete Digital ocean droplets
# http://docs.ansible.com/ansible/digital_ocean_module.html
# Variables: servername, state, drop_id, token
# If spinning up a new droplet use "localhost" as the servername and define the name within the inventory file.
---
- hosts: digitalocean
  vars_prompt:
    - name: token
      prompt: Digital Ocean Token
      private: no
    - name: servername
      prompt: Enter the name of the server
      private: no
    - name: droplet_id
      prompt: enter the dropletid (defaults to 000001)
      default: 000001
    - name: state
      prompt: enter state absent or present
      default: present
      private: no
  tasks:
   - name: Manage "{{servername}}" droplet "{{state}}"
     digital_ocean:
       state: "{{state}}"
       command: droplet

       # The below option makes this idempotent, it will not create duplicate droplets
       # with the same name.
       unique_name: yes

       # ssh_key_ids can be obtained from the digitalocean console, it's the unique key options
       # in brackets () beside the key name.
       # This will add the publick key from the console to root's authorizeds_keyfile during the VM setup
       ssh_key_ids: 6c:3c:f2:57:ed:b6:56:56:91:d2:84:e2:06:c7:43:d6

       # An ID is created on instanciation of a new droplet, captured by the debug messages
       # below. Entering the field with the newly generated ID will stop creation of a new droplet
       # and will make changes if any to the droplet with the ID entered.
       #id: 13507942
       id: "{{droplet_id}}"

       name: "{{servername}}"
       api_token: "{{token}}"
       size_id: 512mb
       region_id: nyc2
       #image_id: ubuntu-14-04-x64
       image_id: centos-7-2-x64
       wait_timeout: 200
     register: my_droplet

   - debug: msg="ID {{ my_droplet.droplet.id }}"
   - debug: msg="IP {{ my_droplet.droplet.ip_address }}"
   - debug: msg="Hostname {{ my_droplet.droplet.name }}"

   ## Add droplet hostname and IP to in memory host inventory management
   ## THis allows other playbooks to inherit those variables.
   - name: Add new host information to local hosts file
     add_host: hostname="{{my_droplet.droplet.ip_address}}"
               groups=OSS
