--- # Fetch remote file
- hosts: srv2
  user: root
  connection: ssh
  gather_facts: yes
  tasks:
   - name: Copy remote file(hosts) to local host into a file labelled (prefix-srv2)
     fetch: src=/etc/hosts dest=./prefix-{{ansible_hostname}} flat=yes validate_checksum=yes
