---
- hosts: '{{servername}}'
  vars:
    zserver: 107.170.116.31
  tasks:
    - name: Download zabbix agent for Ubuntu Precise amd 64 version
      get_url: url=http://repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix/zabbix-agent_2.2.4-1+precise_amd64.deb dest=/tmp mode=644

    - name: Install zabbix agent
      command: dpkg -i /tmp/zabbix-agent_2.2.4-1+precise_amd64.deb
      ignore_errors: yes

    - name: Install zabbix agent from repoository
      apt: pkg=zabbix-agent update_cache=yes cache_valid_time=3600 state=present

    - name:  Configure zabbix agent
      lineinfile: dest=/etc/zabbix/zabbix_agentd.conf state=present regexp="Server=127.0.0.1" line="Server={{zserver}}"

    - name: Configure zabbix agent with zabbix server IP
      lineinfile: dest=/etc/zabbix/zabbix_agentd.conf state=present regexp="Server=localhost" line="Server={{zserver}}"

    # This allow the zabbix server to send configuration information to the agent as well to receive updated informaton
    # example receiving inventory information.
    - name: Configure zabbix to listen on port 10050
      lineinfile: dest=/etc/zabbix/zabbix_agentd.conf state=present insertafter="ListenPort=10050" line="ListenPort=10050"

    # Allow zabbix server to execute commands on the Server
    - name: Modify zabbix configuration file to allow remote command from zabbix Server
      lineinfile: dest=/etc/zabbix/zabbix_agentd.conf state=present insertafter="# EnableRemoteCommands=0" line="EnableRemoteCommands=1"

    - name: Enable debugging
      lineinfile: dest=/etc/zabbix/zabbix_agentd.conf state=present insertafter="# DebugLevel=3" line="DebugLevel=3"

    # Make sure zabbix agent is set to start after a restart
    - name:  Set zabbix agent to start automatically
      service: name=zabbix-agent enabled=yes

    # zabbix agent needs to be restarted to register changes made above
    - name: Restart zabbix agent
      service: name=zabbix-agent state=restarted
