---
# Tasks for configuring Supervisord.

- name: 'include supervisor variables'
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'        # RedHat-6
        - '{{ ansible_os_family }}.yml'                                                 # RedHat
      paths: '../vars'

- name: install supervisor config
  template:
    src: 'tower.conf.j2'
    dest: '{{ sup_conf_location }}'
    force: yes

- name: start/enable supervisord process
  service:
    name: '{{ sup_init_name }}'
    state: started
    enabled: yes

- name: Wait for the supervisor socket
  wait_for:
    path: '{{ sup_socket_location }}'
    timeout: 30

- name: reload supervisord configuration via supervisorctl
  command: supervisorctl reload
